### ISSUE TITLE
Show Previous Form

### ISSUE THREAD

**Issue by orionpal** [HanaBasheer/CSE442-Project#16]
Given a student has already submitted a form, show the form they submitted along with its values.

**Comment by ztperini** [comment]
Not quite implemented yet. Having trouble passing email address needed as parameter to get previous form data. Haven't been able to get sessions to work in php and cookies are too vulnerable. We will have to reconfigure the code-base to make evalForm.html into evalForm.php probably.

**Comment by ztperini** [comment]
6/27
Task Test: 

(1) Go to evaluation form and select a class from the dropdown menu
(2) Submit a form for a teammate.
(3) when the page redirects back to the evaluation form, select the same class and teammate and see if the values match up with the database values for that form.
