### ISSUE TITLE
Give confirmation code its own link

### ISSUE THREAD

**Issue by ztperini** [HanaBasheer/CSE442-Project#28]
Configure codebase to be able to link to our confirmation code page independent of visiting the email entry form.

**Comment by orionpal** [comment]
Test 1:
1) Request code with your email
2) Check to see there is a link in the email
3) Check to see if the link redirects you to the code submission page

**Comment by orionpal** [comment]
Test 2:
1) Go to home page
2) Check to see if there is a link to the code submission page
3) Click the link to see if it redirects you to the code submission page
