### ISSUE TITLE
Add Dropdown box with course options

### ISSUE THREAD

**Issue by orionpal** [HanaBasheer/CSE442-Project#39]
Once student accesses evaluation form, have dropdown menu with courses they are enrolled in.

**Comment by ztperini** [comment]
6/25

Task Test: 

(1) Navigate to evaluation form after receiving confirmation code and entering it.
(2) It should read--choose class with no teammates filled in the bubbles at the beginning.
(3) Check that the classes listed in the dropdown menu are the ones listed for that email in the Student Database
(4) Clicking one of the classes should refresh the page and bring up the list of teammates.
